from . import parcel
from . import shipping_mixin
from . import delivery_mixin
from . import crm_lead
from . import crm_team
from . import project
from . import project_task
from . import product
from . import res_partner
from . import shipping_account
