{
    "name": "Urban mine",
    "category": "Business",
    "summary": "Urban mine offer: people sell their device to the company",
    "version": "16.0.1.0.5",
    "author": "Commown SCIC",
    "license": "AGPL-3",
    "website": "https://github.com/commown/commown-odoo-addons",
    "depends": [
        "account_analytic_tag",
        "commown_devices",
        "commown_shipping",
        "l10n_fr",
        "project",
        "purchase",
        "report_py3o",
        "website",
        "website_sale_coupon",
        "website_recaptcha_v2",
    ],
    "external_dependencies": {},
    "data": [
        "data/mail_templates.xml",
        "data/model.xml",
        "data/parcel_type.xml",
        "data/picking.xml",
        "data/product.xml",
        "data/project.xml",
        "data/coupon.xml",
        "data/registration_page.xml",
        "data/actions.xml",
        "report/report.xml",
    ],
    "demo": [
        "demo/account_analytic_tag.xml",
        "demo/hcaptcha_demo.xml",
    ],
    "installable": True,
}
