{
    "name": "Urban mine",
    "category": "Business",
    "summary": "Urban mine offer: people sell their device to the company",
    "version": "12.0.1.0.3",
    "description": "Urban mine offer: people sell their device to the company",
    "author": "Commown SCIC",
    "license": "AGPL-3",
    "website": "https://commown.coop",
    "depends": [
        "commown_shipping",
        "project",
        "l10n_fr",
        "report_py3o",
        "website_sale_coupon",
        "website_form_builder",
        "website_form_recaptcha",
    ],
    "external_dependencies": {},
    "data": [
        "data/mail_templates.xml",
        "data/model.xml",
        "data/product.xml",
        "data/project.xml",
        "data/coupon.xml",
        "data/report.xml",
        "data/registration_page.xml",
        "data/actions.xml",
    ],
    "installable": True,
}
