{
    "name": "Rental product",
    "category": "Sale",
    "summary": "Define products as rental products",
    "version": "12.0.1.1.11",
    "description": """Rental products have a fixed deposit and recurring price, displayed on the product page""",
    "author": "Commown SCIC",
    "license": "AGPL-3",
    "website": "https://commown.coop",
    "depends": [
        "base_automation",
        "contract_payment_auto",
        "contract_payment_mode",
        "document",
        "ir_attachment_lang",
        "project",
        "product_contract",
        "website_sale",
    ],
    "external_dependencies": {},
    "data": [
        "data/mail_templates.xml",
        "data/project.xml",
        "views/contract.xml",
        "views/portal_contract.xml",
        "views/payment_transaction.xml",
        "views/product_attribute.xml",
        "views/product_template.xml",
        "views/sale_order.xml",
        "views/website_sale_templates.xml",
    ],
    "demo": ["demo/data.xml"],
    "installable": True,
}
