from . import contract
from . import crm_lead
from . import product
from . import product_service_config
from . import project_project
from . import project_task
from . import res_partner
from . import stock_location
from . import stock_picking
from . import stock_production_lot
from . import stock_scrap
from . import stock_move
from . import stock_move_line
from . import wizard_crm_lead_picking
from . import wizard_link_picking_po
from . import wizard_link_po_invoice
from . import wizard_move_line_validation
from . import wizard_project_task_picking
from . import wizard_project_task_to_employee
