from . import contract
from . import crm_lead
from . import picking
from . import product
from . import product_service_config
from . import project_project
from . import project_task
from . import res_partner
from . import stock_production_lot
from . import stock_quant
from . import wizard_crm_lead_picking
from . import wizard_project_task_picking
