from . import account_bank_statement
from . import account_move
from . import contract
from . import crm_lead
from . import ir_http
from . import payment_provider
from . import payment_transaction
from . import product_template
from . import project_task_type
from . import res_partner
from . import res_users
from . import sale_order
from . import website
