from . import test_account_invoice
from . import test_contract
from . import test_controllers
from . import test_crm_lead
from . import test_payment
from . import test_project_task
from . import test_reconciliation_widget
from . import test_res_partner
from . import test_sale_order
from . import test_utm_source
