from . import test_account_move
from . import test_contract
from . import test_controllers
from . import test_crm_lead
from . import test_customer_portal
from . import test_ir_http
from . import test_payment
from . import test_res_partner
from . import test_res_users
from . import test_sale_order
from . import test_simple_reconciliation
