{
    "name": "Website sale B2B",
    "category": "Business",
    "summary": "Adapt website_sale module to mixed B2C/ B2B products",
    "version": "16.0.1.0.4",
    "author": "Commown SCIC",
    "license": "AGPL-3",
    "website": "https://github.com/commown/commown-odoo-addons",
    "depends": [
        "crm",
        "mail",
        "commown_devices",
        "website_sale",
        "website_b2b",
        "customer_manager_base",
    ],
    "external_dependencies": {},
    "data": [
        "data/crm.xml",
        "data/ir_config_parameter.xml",
        "data/mail_template.xml",
        "data/res_partner.xml",
        "views/payment_portal_templates.xml",
        "views/product_pricelist.xml",
        "views/product_template.xml",
        "views/sale_portal_templates.xml",
        "views/website_sale_order.xml",
        "views/website_sale_product.xml",
    ],
    "installable": True,
}
