# Copyright (C) 2021 Commown SCIC (https://commown.coop)
# @author: Florent Cayré
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

{
    "name": "Commown Self Troubleshooting",
    "category": "",
    "version": "16.0.1.0.1",
    "author": "Commown SCIC",
    "license": "AGPL-3",
    "website": "https://github.com/commown/commown-odoo-addons",
    "external_dependencies": {},
    "depends": [
        "base_fontawesome",
        "project",
        "commown_devices",
        "product_rental",
        "web",
    ],
    "data": [
        "data/Assistance/Serenity/form.xml",
        "data/Assistance/Serenity/issue_template.xml",
        "data/Assistance/Generic_Issue/form.xml",
        "data/Assistance/Generic_Issue/issue_template.xml",
        "data/CC/screen/form.xml",
        "data/Commercial/form.xml",
        "data/Commercial/issue_template.xml",
        "data/ContractManagement/termination/form.xml",
        "data/ContractManagement/termination/issue_template.xml",
        "data/ContractManagement/theftandloss/form.xml",
        "data/ContractManagement/theftandloss/issue_template.xml",
        "data/FP2/camera/form.xml",
        "data/FP2/camera/issue_template.xml",
        "data/FP2/micro/form.xml",
        "data/FP2/micro/issue_template.xml",
        "data/FP2/battery/form.xml",
        "data/FP2/battery/issue_template.xml",
        "data/FP3/display/form.xml",
        "data/FP3/display/issue_template.xml",
        "data/FP3/screen/form.xml",
        "data/FP4/screen/form.xml",
        "data/FP5/screen/form.xml",
        "data/GS/day/form.xml",
        "data/GS/day/issue_template.xml",
        "data/Shiftphone/screen/form.xml",
        "data/Smartphone/screen/form.xml",
        "data/Smartphone/screen/issue_template.xml",
        "data/Other/other/form.xml",
        "data/Other/other/issue_template.xml",
        "data/common_steps.xml",
        "data/project.xml",
        "data/tags.xml",
        "data/troubleshooting.xml",
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "views/troubleshooting.xml",
        "views/website_portal_templates.xml",
    ],
    "assets": {
        "web.assets_tests": [
            "/commown_self_troubleshooting/static/src/js/self_troubleshooting_tour.js",
        ],
        "web.assets_frontend": [
            "/commown_self_troubleshooting/static/lib/smartwizard/css/smart_wizard.min.css",
            "/commown_self_troubleshooting/static/lib/smartwizard/css/*_arrows.min.css",
            "/commown_self_troubleshooting/static/lib/smartwizard/js/jquery.smartWizard.js",
            "/commown_self_troubleshooting/static/src/css/self_troubleshooting.css",
            "/commown_self_troubleshooting/static/src/js/setup_wizard.esm.js",
        ],
    },
    "installable": True,
    "application": False,
}
