{
    "name": "Commown SCIC",
    "category": "Business",
    "summary": "Commown SCIC business application",
    "version": "16.0.1.0.15",
    "author": "Commown SCIC",
    "license": "AGPL-3",
    "website": "https://github.com/commown/commown-odoo-addons",
    "depends": [
        "account_loan",
        "attachment_indexation",
        "mail_user_roles_auto_unsubscribe",
        "survey",
        # Commown modules
        "account_invoice_merge_auto_pay",
        "account_move_slimpay_import",
        "account_payment_slimpay_transaction_label",
        "contract_payment_auto_job_post_process",
        "commown_administrative_docs",
        "commown_contract_forecast",
        "commown_discuss",
        "commown_shipping",
        "commown_shipping_crm_contract_delivery_mail",
        "commown_ergonomy_asset",
        "commown_investment_sale",
        "commown_lead_risk_analysis",
        "commown_mass_reconcile",
        "website_sale_payment_slimpay",
        "commown_contract_variable_discount",
        "commown_self_troubleshooting",
        "payment_slimpay_issue",
        "commown_res_partner_sms",
        "commown_payment_token_uniquify",
        "commown_partner_property_accounts",
        "commown_partner_set_invoice_recipient",
        "contract_payment_auto_disable_payment_retry",
        "partner_firstname_portal",
        "product_rental",
        "project_rating_nps",
        "project_task_type_portal_displayed_name",
        "sale_product_email",
        "custom_report",
        "customer_team_manager",
        "slimpay_statements_autoimport",
        "view_contract_unique_issues_tab",
        "website_sale_affiliate_portal",
        "website_sale_affiliate_product_restriction",
        "website_sale_b2b",
        "website_sale_commown_shipping",
        "website_sale_coupon",
        "commown_website_sale_coupon",
        "utm_utils_merge_and_remove_actions",
        # OCA modules
        "account_payment_sale",
        "auth_admin_passkey",
        "auth_signup",
        "bi_sql_editor",
        "contract_queue_job",
        "contract_variable_quantity",
        "phone_validation",
        "mail_debrand",
        "mass_mailing_list_dynamic",
        "mass_mailing_partner",
        "portal",
        "project_task_add_very_high",
        "sale_management",
        "web_m2x_options",
        "web_notify",
        "website_sale_cart_selectable",
    ],
    "demo": [
        "demo/payment_provider.xml",
        "demo/product_rental_pub_category.xml",
    ],
    "data": [
        "data/ir_config_parameter.xml",
        "data/mail_templates.xml",
        "data/payment_provider.xml",
        "data/product.xml",
        "data/product_public_category.xml",
        "data/res_partner_action.xml",
        "security/ir.model.access.csv",
        "views/account_move.xml",
        "views/contract_contract.xml",
        "views/crm_lead.xml",
        "views/ir_attachment.xml",
        "views/payment_portal_templates.xml",
        "views/product_template.xml",
        "views/project_task_portal_templates.xml",
        "views/res_partner.xml",
        "views/website.xml",
        "views/website_portal_templates.xml",
        "views/website_sale_templates.xml",
        "views/website_sale_payment_templates.xml",
        "views/website_site_portal_sale_templates.xml",
        "views/website_templates.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "/commown/static/src/js/slimpay_payment_form_mixin.js",
            "/commown/static/src/css/website_sale.css",
        ],
        "web.assets_backend": [
            "/commown/static/src/js/user_menu_items.esm.js",
        ],
    },
    "installable": True,
    "application": True,
}
