{
    "name": "Commown shipping",
    "category": "Business",
    "summary": "Commown shipping-related features",
    "version": "12.0.1.0.0",
    "author": "Commown SCIC,Odoo Community Association (OCA)",
    "license": "AGPL-3",
    "website": "https://github.com/commown/commown-odoo-addons",
    "depends": [
        "base_automation",
        "sale",
        "website",
        "crm",
        "partner_firstname",
        "project",
        "queue_job",
        "server_environment_data_encryption",
    ],
    "external_dependencies": {"bin": ["pdfjam", "pdftk"]},
    "data": [
        "data/actions.xml",
        "data/cron.xml",
        "data/parcels.xml",
        "data/shipping_accounts.xml",
        "views/crm_team.xml",
        "views/crm_lead.xml",
        "views/product.xml",
        "views/project_project.xml",
        "views/project_task.xml",
        "security/ir.model.access.csv",
    ],
    "demo": ["data/demo.xml"],
    "installable": True,
}
