{
    "name": "Commown shipping",
    "category": "Business",
    "summary": "Commown shipping-related features",
    "version": "16.0.1.0.0",
    "author": "Commown SCIC,Odoo Community Association (OCA)",
    "license": "AGPL-3",
    "website": "https://github.com/commown/commown-odoo-addons",
    "depends": [
        "commown_contractual_issue",
        "commown_res_partner_sms",
        "base_automation",
        "sale",
        "website",
        "crm",
        "partner_firstname",
        "project",
        "queue_job",
        "server_environment",
        "web_ir_actions_act_multi",
    ],
    "external_dependencies": {
        "bin": ["pdfjam", "pdfunite"],
        "python": ["iso8601", "requests_toolbelt"],
    },
    "data": [
        "data/actions.xml",
        "data/cron.xml",
        "data/queue_job_channel.xml",
        "data/queue_job_function_data.xml",
        "data/mail_template.xml",
        "data/shipping_accounts.xml",
        "views/crm_team.xml",
        "views/crm_lead.xml",
        "views/parcels.xml",
        "views/product.xml",
        "views/project_project.xml",
        "views/project_task.xml",
        "views/wizard_print_label.xml",
        "security/ir.model.access.csv",
    ],
    "demo": [
        "demo/mail_template.xml",
        "demo/parcel_type.xml",
    ],
    "installable": True,
}
