from . import keychain
from . import parcel
from . import mixins
from . import crm_lead
from . import project_issue
from . import crm_team
from . import project
from . import product
from . import res_partner
